services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: time-manager-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/cmd:/app/cmd
      - ./backend/internal:/app/internal
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: time-manager-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
      - "7002:7002"
    command: ["npm", "run", "dev"]

  database:
    image: postgres
    container_name: time-manager-database
    env_file:
      - ./database/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    expose:
      - 5432

  redis:
    image: redis
    container_name: time-manager-redis

  adminer:
    image: adminer
    container_name: time-manager-adminer
    expose:
      - 8080

  apigateway:
    image: nginx
    container_name: time-manager-apigateway
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - database
      - backend
      - frontend

volumes:
  db_data: