services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: time-manager-backend
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PROJECT_STATUS: ${PROJECT_STATUS}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend/cmd:/app/cmd
      - ./backend/internal:/app/internal
      - ./backend/pkg:/app/pkg
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: time-manager-frontend
    environment:
      VITE_PROJECT_STATUS: ${PROJECT_STATUS}
      VITE_FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
      - "7002:7002"
    command: ["npm", "run", "dev"]

  database:
    image: postgres
    container_name: time-manager-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      timeout: 2s
      retries: 5
      start_period: 2s

  redis:
    image: redis
    container_name: time-manager-redis

  adminer:
    image: adminer
    container_name: time-manager-adminer
    expose:
      - 8080

  apigateway:
    image: nginx
    container_name: time-manager-apigateway
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
    depends_on:
      - database
      - backend
      - frontend

volumes:
  db_data: