services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: time-manager-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./logs/backend.log:/var/log/app.log
    depends_on:
      - database
    command: >
      sh -c "air 2>&1 | tee -a /var/log/app.log"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: time-manager-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./logs/frontend.log:/var/log/app.log
    ports:
      - "5173:5173"
      - "7002:7002"
    command: >
      sh -c "npm run dev 2>&1 | tee -a /var/log/app.log"

  database:
    image: postgres
    container_name: time-manager-database
    volumes:
      - db_data:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d
      - ./logs/database.log:/var/log/app.log
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: >
      sh -c "docker-entrypoint.sh postgres 2>&1 | tee -a /var/log/app.log"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 5

  redis:
    image: redis
    container_name: time-manager-redis

  adminer:
    image: adminer
    container_name: time-manager-adminer
    expose:
      - 8080

  apigateway:
    image: nginx
    container_name: time-manager-apigateway
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./logs/apigateway.log:/var/log/nginx/access.log
    ports:
      - "8081:80"
    depends_on:
      - database
      - backend
      - frontend
    command: >
      sh -c "nginx -g 'daemon off;' 2>&1 | tee -a /var/log/nginx/access.log"

  migrator:
    image: migrate/migrate:latest
    container_name: time-manager-migrator
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./backend/migrations:/migrations
    env_file:
      - ./backend/.env
    entrypoint: [""]
    command: sh -c "migrate -path=/migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable up"
    restart: "no"
      
volumes:
  db_data: