services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: time-manager-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/cmd:/app/cmd
      - ./backend/internal:/app/internal
      - ./logs/backend.log:/var/log/app.log
    depends_on:
      - database
    command: >
      sh -c "go run cmd/server/main.go 2>&1 | tee -a /var/log/app.log"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: time-manager-frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend/src:/app/src
      - ./logs/frontend.log:/var/log/app.log
    ports:
      - "5173:5173"
      - "7002:7002"
    command: >
      sh -c "npm run dev 2>&1 | tee -a /var/log/app.log"

  database:
    image: postgres
    container_name: time-manager-database
    env_file:
      - ./database/.env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
      - ./logs/database.log:/var/log/app.log
    expose:
      - 5432
      # start the postgres using the user in the env variables
    command: >
      sh -c "docker-entrypoint.sh postgres 2>&1 | tee -a /var/log/app.log"

  redis:
    image: redis
    container_name: time-manager-redis

  adminer:
    image: adminer
    container_name: time-manager-adminer
    expose:
      - 8080

  apigateway:
    image: nginx
    container_name: time-manager-apigateway
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./logs/apigateway.log:/var/log/nginx/access.log
    ports:
      - "8081:80"
    depends_on:
      - database
      - backend
      - frontend
    command: >
      sh -c "nginx -g 'daemon off;' 2>&1 | tee -a /var/log/nginx/access.log"

volumes:
  db_data: