version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: time-manager-backend
    env_file:
      - ./backend/.env
    volumes:
      - ./logs/backend:/logs
    command: >
      sh -c "./app >> /logs/backend.log 2>&1"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: time-manager-frontend
    volumes:
      - ./logs/frontend:/var/log/nginx

  database:
    image: postgres:16
    container_name: time-manager-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./logs/database:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: time-manager-redis

  apigateway:
    image: nginx:alpine
    container_name: time-manager-apigateway
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./logs/apigateway:/var/log/nginx
    ports:
      - "8081:80"
    depends_on:
      - backend

  migrator:
    image: migrate/migrate:latest
    container_name: time-manager-migrator
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/migrations:/migrations
    command: >
      -path=/migrations
      -database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable
      up
    restart: "no"

volumes:
  db_data:
